name: Deploy Test Technique Front

# Déclenchement du workflow sur push dans la branche main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout du code
      - uses: actions/checkout@v4

      # Déploiement avec ton action
      - name: Deploy Test Technique Front
        uses: PaulCollas/test_technique_front@v1.0.0
        with:
          checkout: true
          path: dist/test-technique-front/browser
          install_command: npm ci
          build_command: npm run build -- --base-href=/test-technique-front/
          caching: true
