- name: Deploy Test Technique Front
  uses: PaulCollas/test_technique_front@v1.0.0
  with:
    checkout: true

    # dossier généré par Angular 20
    path: dist/test-technique-front/browser

    # installation des deps
    install_command: npm ci

    # build Angular 20 + base-href pour GitHub Pages
    build_command: npm run build -- --base-href=/test-technique-front/

    # cache npm
    caching: true
